### ISSUE TITLE
我改了下你的代码，做了linux 64 的，有需要的联系我。

### ISSUE THREAD

**Issue by aicccode** [CongCongBig/JSeetaface6#2]
我改了下你的代码，做了linux 64 的，有需要的联系我。

**Comment by young0704** [comment]
大佬，能共享一下吗，不胜感激。455644883@qq.com

**Comment by CongCongBig** [comment]
> 我改了下你的代码，做了linux 64的，有需要的联系我。

抱歉，才看到你发的信息，如果不介意可以从readme去到gitee联系我。github找不到私信功能。哈哈

**Comment by aicccode** [comment]
> 大佬，能共享一下吗，不胜感激。[455644883@qq.com](mailto:455644883@qq.com)

晚点我推到github仓库，我正在添加移动端支持，还没放完，最进忙。

**Comment by aicccode** [comment]
> > 我改了下你的代码，做了linux 64的，有需要的联系我。
> 
> 抱歉，才看到你发的信息，如果不介意可以从readme去到gitee联系我。github找不到私信功能。哈哈

客气哈，我没用gitee

**Comment by h3clikejava** [comment]
开源吧朋友，太需要了

**Comment by miaoyizi** [comment]
> > 大佬，能共享一下吗，不胜感激。[455644883@qq.com](mailto:455644883@qq.com)
> 
> 晚点我推到github仓库，我正在添加移动端支持，还没放完，最进忙。

您好，请问下Linux下面的linux 64  下面的lib 是从源码编译出来对应的so吗？
